version: "3.7"

services:
  postgres:
    container_name: "${SERVICE_NAME}-postgres"
    image: postgres:14.0-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/postgres:/data/postgres
      - ./seed:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - PGDATA=/data/postgres